runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app --config gunicorn.conf.py

runtime_config:
  python_version: 3
    
resources:
  cpu: 1
  memory_gb: 2.5
  disk_size_gb: 15

automatic_scaling:
  max_num_instances: 1

env_variables:
  SECRET_KEY: <SECRET_KEY>

